package com.openDams.bean;

// Generated 14-gen-2010 12.17.27 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * ArchiveTypes generated by hbm2java
 */
public class ArchiveTypes extends ArchiveType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idArchiveType;
	private String description;
	private byte[] generic_index_configuration_xml;
	private byte[] generic_title_configuration_xml;
	private Set<Archives> archiveses = new HashSet<Archives>(0);

	public ArchiveTypes() {
	}

	public ArchiveTypes(String description) {
		this.description = description;
	}

	public ArchiveTypes(String description, Set<Archives> archiveses) {
		this.description = description;
		this.archiveses = archiveses;
	}

	public Integer getIdArchiveType() {
		return this.idArchiveType;
	}

	public void setIdArchiveType(Integer idArchiveType) {
		this.idArchiveType = idArchiveType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getGeneric_index_configuration_xml() {
		return generic_index_configuration_xml;
	}

	public void setGeneric_index_configuration_xml(
			byte[] genericIndexConfigurationXml) {
		generic_index_configuration_xml = genericIndexConfigurationXml;
	}

	public byte[] getGeneric_title_configuration_xml() {
		return generic_title_configuration_xml;
	}

	public void setGeneric_title_configuration_xml(
			byte[] genericTitleConfigurationXml) {
		generic_title_configuration_xml = genericTitleConfigurationXml;
	}

	public Set<Archives> getArchiveses() {
		return this.archiveses;
	}

	public void setArchiveses(Set<Archives> archiveses) {
		this.archiveses = archiveses;
	}

}
