package com.openDams.bean;

// Generated 18-dic-2009 11.35.39 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;



/**
 * Archives generated by hbm2java
 */
public class Archives implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idArchive;
	private ArchiveTypes archiveTypes;
	private ArchiveIdentities archiveIdentities;
	private ArchiveGroup archiveGroup;
	private String label;
	private String description;
	private String archiveXmlPrefix;
	private Boolean use_default_index;
	private Integer archiveOrder;
	private String archiveClass;
	private boolean offline;
	private XmlId xmlId;
	private int countDeleted = 0;
	private Set<Records> recordses = new HashSet<Records>(0);
	private Set<Companies> companieses = new HashSet<Companies>(0);
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);
	private Set<ArchiveUserRole> archiveUserRoles = new HashSet<ArchiveUserRole>(0);
	private Set<Notes> noteses = new HashSet<Notes>(0);
	public Archives() {
	}

	public Archives(ArchiveTypes archiveTypes,
			ArchiveIdentities archiveIdentities, ArchiveGroup archiveGroup, String label) {
		this.archiveTypes = archiveTypes;
		this.archiveIdentities = archiveIdentities;
		this.archiveGroup = archiveGroup;
		this.label = label;
	}

	public Archives(ArchiveTypes archiveTypes,
			ArchiveIdentities archiveIdentities, ArchiveGroup archiveGroup, String label,
			String description, Set<Records> recordses, XmlId xmlId,
			Set<Companies> companieses, Set<UserRoles> userRoleses) {
		this.archiveTypes = archiveTypes;
		this.archiveIdentities = archiveIdentities;
		this.archiveGroup = archiveGroup;
		this.label = label;
		this.description = description;
		this.recordses = recordses;
		this.xmlId = xmlId;
		this.companieses = companieses;
		this.userRoleses = userRoleses;
	}

	public Integer getIdArchive() {
		return this.idArchive;
	}

	public void setIdArchive(Integer idArchive) {
		this.idArchive = idArchive;
	}
	public ArchiveTypes getArchiveTypes() {
		return this.archiveTypes;
	}

	public void setArchiveTypes(ArchiveTypes archiveTypes) {
		this.archiveTypes = archiveTypes;
	}

	public ArchiveIdentities getArchiveIdentities() {
		return this.archiveIdentities;
	}

	public void setArchiveIdentities(ArchiveIdentities archiveIdentities) {
		this.archiveIdentities = archiveIdentities;
	}
	public ArchiveGroup getArchiveGroup() {
		return this.archiveGroup;
	}

	public void setArchiveGroup(ArchiveGroup archiveGroup) {
		this.archiveGroup = archiveGroup;
	}
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Records> getRecordses() {
		return this.recordses;
	}

	public void setRecordses(Set<Records> recordses) {
		this.recordses = recordses;
	}

	public Boolean getUse_default_index() {
		return use_default_index;
	}

	public void setUse_default_index(Boolean useDefaultIndex) {
		use_default_index = useDefaultIndex;
	}
	
	public Integer getArchiveOrder() {
		return this.archiveOrder;
	}

	public void setArchiveOrder(Integer archiveOrder) {
		this.archiveOrder = archiveOrder;
	}
	
	public XmlId getXmlId() {
		return xmlId;
	}

	public void setXmlId(XmlId xmlId) {
		this.xmlId = xmlId;
	}
	public Set<Companies> getCompanieses() {
		return this.companieses;
	}

	public void setCompanieses(Set<Companies> companieses) {
		this.companieses = companieses;
	}

	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

	public String getArchiveXmlPrefix() {
		return archiveXmlPrefix;
	}

	public void setArchiveXmlPrefix(String archiveXmlPrefix) {
		this.archiveXmlPrefix = archiveXmlPrefix;
	}

	public Set<ArchiveUserRole> getArchiveUserRoles() {
		return archiveUserRoles;
	}

	public void setArchiveUserRoles(Set<ArchiveUserRole> archiveUserRoles) {
		this.archiveUserRoles = archiveUserRoles;
	}
	public Set<Notes> getNoteses() {
		return this.noteses;
	}

	public void setNoteses(Set<Notes> noteses) {
		this.noteses = noteses;
	}

	public String getArchiveClass() {
		return archiveClass;
	}

	public void setArchiveClass(String archiveClass) {
		this.archiveClass = archiveClass;
	}
	public boolean isOffline() {
		return this.offline;
	}

	public void setOffline(boolean offline) {
		this.offline = offline;
	}

	public int getCountDeleted() {
		return countDeleted;
	}

	public void setCountDeleted(int countDeleted) {
		this.countDeleted = countDeleted;
	}
}
