package com.openDams.bean;

// Generated 14-gen-2010 12.17.27 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * ArchiveIdentities generated by hbm2java
 */
public class ArchiveIdentities extends ArchiveIdentity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idArchiveIdentity;
	private String description;
	private Set<Archives> archiveses = new HashSet<Archives>(0);

	public ArchiveIdentities() {
	}

	public ArchiveIdentities(String description) {
		this.description = description;
	}

	public ArchiveIdentities(String description, Set<Archives> archiveses) {
		this.description = description;
		this.archiveses = archiveses;
	}

	public Integer getIdArchiveIdentity() {
		return this.idArchiveIdentity;
	}

	public void setIdArchiveIdentity(Integer idArchiveIdentity) {
		this.idArchiveIdentity = idArchiveIdentity;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Archives> getArchiveses() {
		return this.archiveses;
	}

	public void setArchiveses(Set<Archives> archiveses) {
		this.archiveses = archiveses;
	}

}
