package com.openDams.bean;

// Generated 20-gen-2011 13.02.45 by Hibernate Tools 3.2.4.GA

/**
 * ArchiveUserRole generated by hbm2java
 */
public class ArchiveUserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4817345125283045229L;
	private ArchiveUserRoleId id;
	private Archives archives;
	private Roles roles;
	private Users users;

	public ArchiveUserRole() {
	}

	public ArchiveUserRole(ArchiveUserRoleId id, Archives archives,Roles roles, Users users) {
		this.id = id;
		this.archives = archives;
		this.roles = roles;
		this.users = users;
	}

	public ArchiveUserRoleId getId() {
		return this.id;
	}

	public void setId(ArchiveUserRoleId id) {
		this.id = id;
	}

	public Archives getArchives() {
		return this.archives;
	}

	public void setArchives(Archives archives) {
		this.archives = archives;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
