package com.openDams.bean;

// Generated 12-mag-2010 11.42.27 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Companies generated by hbm2java
 */
public class Companies implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1150228471131875453L;
	private Integer idCompany;
	private String acronym;
	private String companyName;
	private String imageName;
	private Set<Archives> archiveses = new HashSet<Archives>(0);
	private Set<Departments> departmentses = new HashSet<Departments>(0);
	private Set<Users> userses = new HashSet<Users>(0);

	public Companies() {
	}

	public Companies(String acronym, String companyName) {
		this.acronym = acronym;
		this.companyName = companyName;
	}

	public Companies(String acronym, String companyName,
			Set<Archives> archiveses, Set<Users> userses) {
		this.acronym = acronym;
		this.companyName = companyName;
		this.archiveses = archiveses;
		this.userses = userses;
	}

	public Integer getIdCompany() {
		return this.idCompany;
	}

	public void setIdCompany(Integer idCompany) {
		this.idCompany = idCompany;
	}

	public String getAcronym() {
		return this.acronym;
	}

	public void setAcronym(String acronym) {
		this.acronym = acronym;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getImageName() {
		return imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	public Set<Archives> getArchiveses() {
		return this.archiveses;
	}

	public void setArchiveses(Set<Archives> archiveses) {
		this.archiveses = archiveses;
	}
	public Set<Departments> getDepartmentses() {
		return this.departmentses;
	}

	public void setDepartmentses(Set<Departments> departmentses) {
		this.departmentses = departmentses;
	}
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
