package com.openDams.bean;

// Generated 6-ott-2010 11.13.48 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;



/**
 * Departments generated by hbm2java
 */
public class Departments implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDepartment;
	private Companies companies;
	private String acronym;
	private String description;
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<Messages> messageses = new HashSet<Messages>(0);
	private Set<Notes> noteses = new HashSet<Notes>(0);
	private SearchSequentials searchSequentials;

	public Departments() {
	}

	public Departments(Companies companies, String acronym, String description,SearchSequentials searchSequentials) {
		this.companies = companies;
		this.acronym = acronym;
		this.description = description;
	}

	public Departments(Companies companies, String acronym, String description,
			Set<Users> userses) {
		this.companies = companies;
		this.acronym = acronym;
		this.description = description;
		this.userses = userses;
	}

	public Integer getIdDepartment() {
		return this.idDepartment;
	}

	public void setIdDepartment(Integer idDepartment) {
		this.idDepartment = idDepartment;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getAcronym() {
		return this.acronym;
	}

	public void setAcronym(String acronym) {
		this.acronym = acronym;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}
	public SearchSequentials getSearchSequentials() {
		return this.searchSequentials;
	}

	public void setSearchSequentials(SearchSequentials searchSequentials) {
		this.searchSequentials = searchSequentials;
	}
	public Set<Messages> getMessageses() {
		return this.messageses;
	}

	public void setMessageses(Set<Messages> messageses) {
		this.messageses = messageses;
	}

	public Set<Notes> getNoteses() {
		return this.noteses;
	}

	public void setNoteses(Set<Notes> noteses) {
		this.noteses = noteses;
	}
}
