package com.openDams.bean;

// Generated 8-apr-2011 13.33.29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ImportHistory generated by hbm2java
 */
public class ImportHistory implements java.io.Serializable {

	private static final long serialVersionUID = -5030113518571956597L;
	private String uri;
	private String type;
	private Date creationDate;
	private Date modificationDate;
	private boolean importStatus;
	
	
	private boolean applicationStatus;
	private String message;

	public ImportHistory() {
	}

	public ImportHistory(String uri, String type) {
		this.uri = uri;
		this.type = type;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	} 
	public void setMessage(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	public Date getModificationDate() {
		return modificationDate;
	} 

	public void setImportStatus(boolean importStatus) {
		this.importStatus = importStatus;
	}

	public boolean isImportStatus() {
		return importStatus;
	}

	public void setApplicationStatus(boolean applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	public boolean isApplicationStatus() {
		return applicationStatus;
	}

}
