package com.openDams.bean;

// Generated 5-mar-2012 16.54.06 by Hibernate Tools 3.2.4.GA

import java.util.Date;





/**
 * Messages generated by hbm2java
 */
public class Messages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1134842159674169800L;
	private Integer idMessage;
	private MessageTypes messageTypes;
	private Departments departments;
	private Users usersByRefIdUserSender;
	private Users usersByRefIdUser;
	private Users usersByRefIdUserTo;
	private String messageText;
	private Date date;
	private String object;
	private boolean readed;
	private boolean modal;
	private Date validity;
	private boolean interest;
	public Messages() {
	}

	public Messages(MessageTypes messageTypes, String messageText, Date date,
			String object, boolean readed) {
		this.messageTypes = messageTypes;
		this.messageText = messageText;
		this.date = date;
		this.object = object;
		this.readed = readed;
	}

	public Messages(MessageTypes messageTypes, Departments departments,
			Users usersByRefIdUserSender, Users usersByRefIdUser,
			String messageText, Date date, String object, boolean readed) {
		this.messageTypes = messageTypes;
		this.departments = departments;
		this.usersByRefIdUserSender = usersByRefIdUserSender;
		this.usersByRefIdUser = usersByRefIdUser;
		this.messageText = messageText;
		this.date = date;
		this.object = object;
		this.readed = readed;
	}

	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	public MessageTypes getMessageTypes() {
		return this.messageTypes;
	}

	public void setMessageTypes(MessageTypes messageTypes) {
		this.messageTypes = messageTypes;
	}

	public Departments getDepartments() {
		return this.departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}

	public Users getUsersByRefIdUserSender() {
		return this.usersByRefIdUserSender;
	}

	public void setUsersByRefIdUserSender(Users usersByRefIdUserSender) {
		this.usersByRefIdUserSender = usersByRefIdUserSender;
	}

	public Users getUsersByRefIdUser() {
		return this.usersByRefIdUser;
	}

	public void setUsersByRefIdUser(Users usersByRefIdUser) {
		this.usersByRefIdUser = usersByRefIdUser;
	}

	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getObject() {
		return this.object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	public boolean isReaded() {
		return this.readed;
	}

	public void setReaded(boolean readed) {
		this.readed = readed;
	}

	public boolean isModal() {
		return modal;
	}

	public void setModal(boolean modal) {
		this.modal = modal;
	}

	public Date getValidity() {
		return this.validity;
	}

	public void setValidity(Date validity) {
		this.validity = validity;
	}
	
	public boolean isInterest() {
		return this.interest;
	}

	public void setInterest(boolean interest) {
		this.interest = interest;
	}
	public Users getUsersByRefIdUserTo() {
		return this.usersByRefIdUserTo;
	}

	public void setUsersByRefIdUserTo(Users usersByRefIdUserTo) {
		this.usersByRefIdUserTo = usersByRefIdUserTo;
	}
}
