package com.openDams.bean;

// Generated 3-gen-2012 16.33.25 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MessageTypes generated by hbm2java
 */
public class MessageTypes implements java.io.Serializable {

	public static final int PERSONAL_MESSAGE = 1;
	public static final int DEPARTMENT_MESSAGE = 2;
	public static final int SYSTEM_MESSAGE = 3;
	
	private static final long serialVersionUID = 1L;
	private Integer idMessageType;
	private String messageLabel;
	private Set<Messages> messageses = new HashSet<Messages>(0);

	public MessageTypes() {
	}

	public MessageTypes(String messageLabel) {
		this.messageLabel = messageLabel;
	}

	public MessageTypes(String messageLabel, Set<Messages> messageses) {
		this.messageLabel = messageLabel;
		this.messageses = messageses;
	}

	public Integer getIdMessageType() {
		return this.idMessageType;
	}

	public void setIdMessageType(Integer idMessageType) {
		this.idMessageType = idMessageType;
	}

	public String getMessageLabel() {
		return this.messageLabel;
	}

	public void setMessageLabel(String messageLabel) {
		this.messageLabel = messageLabel;
	}

	public Set<Messages> getMessageses() {
		return this.messageses;
	}

	public void setMessageses(Set<Messages> messageses) {
		this.messageses = messageses;
	}

}
