package com.openDams.bean;

import java.util.Date;




// Generated 3-gen-2012 16.33.25 by Hibernate Tools 3.2.4.GA

/**
 * Notes generated by hbm2java
 */
public class Notes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idNote;
	private Departments departments;
	private Archives archives;
	private NoteTypes noteTypes;
	private Records records;
	private Users users;
	private String noteText;
	private Date date;
	private String noteTitle;

	public Notes() {
	}

	public Notes(String noteText, Date date) {
		this.noteText = noteText;
		this.date = date;
	}

	public Notes(Departments departments, Archives archives, Records records,
			Users users, String noteText, Date date) {
		this.departments = departments;
		this.archives = archives;
		this.records = records;
		this.users = users;
		this.noteText = noteText;
		this.date = date;
	}

	public Integer getIdNote() {
		return this.idNote;
	}

	public void setIdNote(Integer idNote) {
		this.idNote = idNote;
	}

	public Departments getDepartments() {
		return this.departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}

	public Archives getArchives() {
		return this.archives;
	}

	public void setArchives(Archives archives) {
		this.archives = archives;
	}
	public NoteTypes getNoteTypes() {
		return this.noteTypes;
	}

	public void setNoteTypes(NoteTypes noteTypes) {
		this.noteTypes = noteTypes;
	}
	public Records getRecords() {
		return this.records;
	}

	public void setRecords(Records records) {
		this.records = records;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getNoteText() {
		return this.noteText;
	}

	public void setNoteText(String noteText) {
		this.noteText = noteText;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	
	public String getNoteTitle() {
		return this.noteTitle;
	}

	public void setNoteTitle(String noteTitle) {
		this.noteTitle = noteTitle;
	}

}
