package com.openDams.bean;

// Generated 10-gen-2012 11.42.25 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * NoteTypes generated by hbm2java
 */
public class NoteTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4575374505535158464L;
	private Integer idNoteType;
	private String label;
	private Set<Notes> noteses = new HashSet<Notes>(0);

	public NoteTypes() {
	}

	public NoteTypes(String label) {
		this.label = label;
	}

	public NoteTypes(String label, Set<Notes> noteses) {
		this.label = label;
		this.noteses = noteses;
	}

	public Integer getIdNoteType() {
		return this.idNoteType;
	}

	public void setIdNoteType(Integer idNoteType) {
		this.idNoteType = idNoteType;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Set<Notes> getNoteses() {
		return this.noteses;
	}

	public void setNoteses(Set<Notes> noteses) {
		this.noteses = noteses;
	}

}
