package com.openDams.bean;

// Generated 18-dic-2009 11.35.39 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * RecordTypes generated by hbm2java
 */
public class RecordTypes extends RecordType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRecordType;
	private String description;
	private Set<Records> recordses = new HashSet<Records>(0);

	public RecordTypes() {
	}
	public RecordTypes(Integer idRecordType) {
		this.idRecordType=idRecordType;
	}
	public RecordTypes(String description, Set<Records> recordses) {
		this.description = description;
		this.recordses = recordses;
	}

	public Integer getIdRecordType() {
		return this.idRecordType;
	}

	public void setIdRecordType(Integer idRecordType) {
		this.idRecordType = idRecordType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Records> getRecordses() {
		return this.recordses;
	}

	public void setRecordses(Set<Records> recordses) {
		this.recordses = recordses;
	}

}
