package com.openDams.bean;

// Generated 18-dic-2009 11.35.39 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * RelationTypes generated by hbm2java
 */
public class RelationTypes extends RelationType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRelationType;
	private String label;
	private String description;
	private Set<Relations> relationses = new HashSet<Relations>(0);

	public RelationTypes() {
	}

	public RelationTypes(String label, String description,
			Set<Relations> relationses) {
		this.label = label;
		this.description = description;
		this.relationses = relationses;
	}

	public Integer getIdRelationType() {
		return this.idRelationType;
	}

	public void setIdRelationType(Integer idRelationType) {
		this.idRelationType = idRelationType;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Relations> getRelationses() {
		return this.relationses;
	}

	public void setRelationses(Set<Relations> relationses) {
		this.relationses = relationses;
	}

	@Override
	public String toString() {
		return "RelationTypes [idRelationType=" + idRelationType + ", label=" + label + ", description=" + description + ", relationses=" + relationses + "]";
	}
}
