package com.openDams.bean;

// Generated 12-mag-2010 11.42.27 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1950654973165642049L;
	private Integer idRole;
	private String roleName;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);
	private Set<ArchiveUserRole> archiveUserRoles = new HashSet<ArchiveUserRole>(0);
	public Roles() {
	}

	public Roles(String roleName) {
		this.roleName = roleName;
	}

	public Roles(String roleName, Set<UserRoles> userRoleses) {
		this.roleName = roleName;
		this.userRoleses = userRoleses;
	}

	public Integer getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Integer idRole) {
		this.idRole = idRole;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

	public Set<ArchiveUserRole> getArchiveUserRoles() {
		return archiveUserRoles;
	}

	public void setArchiveUserRoles(Set<ArchiveUserRole> archiveUserRoles) {
		this.archiveUserRoles = archiveUserRoles;
	}

}
