package com.openDams.bean;

// Generated 3-ott-2011 13.08.28 by Hibernate Tools 3.2.4.GA

/**
 * SearchSequentials generated by hbm2java
 */
public class SearchSequentials implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8715398195255780139L;
	private int refIdDepartment;
	private Departments departments;
	private int sequentialNumber;
	private String prefix;

	public SearchSequentials() {
	}

	public SearchSequentials(Departments departments, int sequentialNumber,
			String prefix) {
		this.departments = departments;
		this.sequentialNumber = sequentialNumber;
		this.prefix = prefix;
	}

	public int getRefIdDepartment() {
		return this.refIdDepartment;
	}

	public void setRefIdDepartment(int refIdDepartment) {
		this.refIdDepartment = refIdDepartment;
	}

	public Departments getDepartments() {
		return this.departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}

	public int getSequentialNumber() {
		return this.sequentialNumber;
	}

	public void setSequentialNumber(int sequentialNumber) {
		this.sequentialNumber = sequentialNumber;
	}

	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

}
