package com.openDams.bean;

// Generated 12-mag-2010 12.10.15 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * UsersPrifile generated by hbm2java
 */
public class UsersProfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3814181790408645317L;
	private int refIdUser;
	private Users users;
	private String name;
	private String lastname;
	private String language;
	private String email;
	private Date birthDate;
	private String telephoneNumber;

	public UsersProfile() {
	}

	public UsersProfile(Users users) {
		this.users = users;
	}

	public UsersProfile(Users users, String name, String lastname,
			String language, String email, Date birthDate,
			String telephoneNumber) {
		this.users = users;
		this.name = name;
		this.lastname = lastname;
		this.language = language;
		this.email = email;
		this.birthDate = birthDate;
		this.telephoneNumber = telephoneNumber;
	}

	public int getRefIdUser() {
		return this.refIdUser;
	}

	public void setRefIdUser(int refIdUser) {
		this.refIdUser = refIdUser;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getTelephoneNumber() {
		return this.telephoneNumber;
	}

	public void setTelephoneNumber(String telephoneNumber) {
		this.telephoneNumber = telephoneNumber;
	}

}
