package com.openDams.bean;

// Generated 12-mag-2010 11.42.27 by Hibernate Tools 3.2.4.GA

/**
 * UserRoles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4859773996635404486L;
	private int refIdUser;
	private Roles roles;
	private Users users;

	public UserRoles() {
	}

	public UserRoles(Roles roles, Users users) {
		this.roles = roles;
		this.users = users;
	}

	public int getRefIdUser() {
		return this.refIdUser;
	}

	public void setRefIdUser(int refIdUser) {
		this.refIdUser = refIdUser;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
