package com.openDams.bean;

// Generated 12-mag-2010 12.10.15 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;


/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7228715134379378823L;
	private Integer idUser;
	private Companies companies;
	private Departments departments;
	private String username;
	private String password;
	private boolean active;
	private UsersProfile usersProfile;
	private UserRoles userRoles;
	private Set<ArchiveUserRole> archiveUserRoles = new HashSet<ArchiveUserRole>(0);
	private Set<Notes> noteses = new HashSet<Notes>(0);
	private Set<Messages> messageses = new HashSet<Messages>(0);
	public Users() {
	}

	public Users(Companies companies, String username, String password,
			boolean active) {
		this.companies = companies;
		this.username = username;
		this.password = password;
		this.active = active;
	}

	public Users(Companies companies, String username, String password,
			boolean active, UsersProfile usersProfile,
			UserRoles userRoles) {
		this.companies = companies;
		this.username = username;
		this.password = password;
		this.active = active;
		this.usersProfile = usersProfile;
		this.userRoles = userRoles;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}
	public Departments getDepartments() {
		return this.departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}
	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public UsersProfile getUsersProfile() {
		return this.usersProfile;
	}

	public void setUsersProfile(UsersProfile usersProfile) {
		this.usersProfile = usersProfile;
	}

	public UserRoles getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(UserRoles userRoles) {
		this.userRoles = userRoles;
	}

	public Set<ArchiveUserRole> getArchiveUserRoles() {
		return archiveUserRoles;
	}

	public void setArchiveUserRoles(Set<ArchiveUserRole> archiveUserRoles) {
		this.archiveUserRoles = archiveUserRoles;
	}
    public int getArchiveRole(int id_archive){
    	Iterator<ArchiveUserRole> iterator = archiveUserRoles.iterator();
    	while (iterator.hasNext()) {
			ArchiveUserRole archiveUserRole = (ArchiveUserRole) iterator.next();
			if(archiveUserRole.getArchives().getIdArchive()==id_archive)
				return archiveUserRole.getRoles().getIdRole();
		}
    	return 0;
    }
    public Set<Notes> getNoteses() {
		return this.noteses;
	}

	public void setNoteses(Set<Notes> noteses) {
		this.noteses = noteses;
	}

	public Set<Messages> getMessageses() {
		return this.messageses;
	}

	public void setMessageses(Set<Messages> messageses) {
		this.messageses = messageses;
	}
}
