package com.openDams.bean;

// Generated 24-feb-2010 16.45.09 by Hibernate Tools 3.2.4.GA

/**
 * XmlId generated by hbm2java
 */
public class XmlId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int refIdArchive;
	private Archives archives;
	private int idXml;

	public XmlId() {
	}

	public XmlId(Archives archives, int idXml) {
		this.archives = archives;
		this.idXml = idXml;
	}

	public int getRefIdArchive() {
		return this.refIdArchive;
	}

	public void setRefIdArchive(int refIdArchive) {
		this.refIdArchive = refIdArchive;
	}

	public Archives getArchives() {
		return this.archives;
	}

	public void setArchives(Archives archives) {
		this.archives = archives;
	}

	public int getIdXml() {
		return this.idXml;
	}

	public void setIdXml(int idXml) {
		this.idXml = idXml;
	}

}
